[project]
name = "aivis-speech-api"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.8",
    "httpx>=0.28.1",
    "lameenc>=1.8.1",
    "uvicorn>=0.34.0",
]
